BearingApp/Controllers/MeebaInfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BearingApp.Models;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;

namespace BearingApp.Controllers
{
    public class MeebaInfoesController : Controller
    {
        private BearingAppContext db = new BearingAppContext();

        // GET: MeebaInfoes
        public ActionResult Index()
        {
            var userAppt = 0;
            var userSocial = 0;
            var userWork = 0;
            var userPersonal = 0;
            var userEvent = 0;
            var userOther = 0;
            var userInner = 10;
            var userOuter = 10;


            var currentUser = User.Identity.GetUserId();
            var userMeeba = from user in db.MeebaInfoes
                            where user.userID == currentUser
                            select user;

            foreach(var appointment in userMeeba)
            {
                userAppt += appointment.apptInt;
            }

            foreach (var social in userMeeba)
            {
                userSocial += social.socInt;
            }

            foreach (var work in userMeeba)
            {
                userWork += work.workInt;
            }

            foreach (var personal in userMeeba)
            {
                userPersonal += personal.persInt;
            }

            foreach (var evt in userMeeba)
            {
                userEvent += evt.evtInt;
            }

            foreach (var other in userMeeba)
            {
                userOther += other.otherInt;
            }

            foreach (var inner in userMeeba)
            {
                userInner += inner.innerInt;
            }

            foreach (var outer in userMeeba)
            {
                userOuter += outer.OuterInt;
            }

            ViewData["Appointments"] = userAppt;
            ViewData["Social"] = userSocial;
            ViewData["Work"] = userWork;
            ViewData["Events"] = userEvent;
            ViewData["Personal"] = userPersonal;
            ViewData["Other"] = userOther;
            ViewData["Inner"] = userInner;
            ViewData["Outer"] = userOuter;
            return View();
        }

        // GET: MeebaInfoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeebaInfo meebaInfo = db.MeebaInfoes.Find(id);
            if (meebaInfo == null)
            {
                return HttpNotFound();
            }
            return View(meebaInfo);
        }

        // GET: MeebaInfoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MeebaInfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,itemName,category,pull,apptInt,workInt,socInt,evtInt,persInt,otherInt,innerInt,OuterInt")] MeebaInfo meebaInfo)
        {
            if (ModelState.IsValid)
            {
                
                db.MeebaInfoes.Add(meebaInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(meebaInfo);
        }

        // GET: MeebaInfoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeebaInfo meebaInfo = db.MeebaInfoes.Find(id);
            if (meebaInfo == null)
            {
                return HttpNotFound();
            }
            return View(meebaInfo);
        }

        // POST: MeebaInfoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,itemName,category,pull,apptInt,workInt,socInt,evtInt,persInt,otherInt,innerInt,OuterInt")] MeebaInfo meebaInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(meebaInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(meebaInfo);
        }

        // GET: MeebaInfoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MeebaInfo meebaInfo = db.MeebaInfoes.Find(id);
            if (meebaInfo == null)
            {
                return HttpNotFound();
            }
            return View(meebaInfo);
        }

        // POST: MeebaInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MeebaInfo meebaInfo = db.MeebaInfoes.Find(id);
            db.MeebaInfoes.Remove(meebaInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PostEvent([Bind(Include = "ID,itemName,category,pull")]MeebaInfo meeba)
        {
            switch (meeba.category)
            {
                case "Social":
                    meeba.socInt++;
                    break;

                case "Appointment":
                    meeba.apptInt++;
                    break;

                case "Work":
                    meeba.workInt++;
                    break;

                case "Events":
                    meeba.evtInt++;
                    break;

                case "Other":
                    meeba.otherInt++;
                    break;

                case "Personal":
                    meeba.persInt++;
                    break;

            }

            switch (meeba.pull)
            {
                case "Inner":
                    meeba.innerInt++;
                    meeba.OuterInt--;
                    break;

                case "Outer":
                    meeba.OuterInt++;
                    meeba.innerInt--;
                    break;
            }

            meeba.userID = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                
                db.MeebaInfoes.Add(meeba);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return new JsonResult() { Data = JsonConvert.SerializeObject(meeba.ID), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
               
    }
        

        


    protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BearingApp/Views/MeebaInfoes/Create.cshtml
@model BearingApp.Models.MeebaInfo

@{
    ViewBag.Title = "Create";
}

<form method="post" action="@Url.Action("PostEvent", "MeebaInfoes")">
    Name: <input type="text" name="itemName" /><br />
    Category: <select name="category">
    <option value="Appointment">Appointment</option>
    <option value="Social">Social</option>
    <option value="Event">Event</option>
    <option value="Personal">Personal</option>
    <option value="Work">Work</option>
    <option value="Other">Other</option>
    </select><br />

    Polarity: <select name="pull">
    <option value="innne">Inner</option>
    <option value="Outer">Outer</option>
    </select><br />

    <input type="submit" value="Create Event" />
</form>

BearingApp/Views/MeebaInfoes/Delete.cshtml
@model BearingApp.Models.MeebaInfo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MeebaInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.itemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.itemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pull)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pull)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apptInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apptInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.workInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.workInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.socInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.socInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.evtInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evtInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.persInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.persInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.otherInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.otherInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.innerInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.innerInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OuterInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OuterInt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BearingApp/Views/MeebaInfoes/Details.cshtml
@model BearingApp.Models.MeebaInfo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MeebaInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.itemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.itemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pull)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pull)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apptInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apptInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.workInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.workInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.socInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.socInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.evtInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.evtInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.persInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.persInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.otherInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.otherInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.innerInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.innerInt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OuterInt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OuterInt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BearingApp/Views/MeebaInfoes/Edit.cshtml
@model BearingApp.Models.MeebaInfo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MeebaInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.itemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.itemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.itemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pull, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pull, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pull, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apptInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apptInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apptInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.workInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.workInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.workInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.socInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.socInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.socInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.evtInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.evtInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.evtInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.persInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.persInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.persInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.otherInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.otherInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.otherInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.innerInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.innerInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.innerInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OuterInt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OuterInt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OuterInt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BearingApp/Views/MeebaInfoes/Index.cshtml
 @model IEnumerable<BearingApp.Models.MeebaInfo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<canvas id="myChart" width="400" height="400"></canvas>
<canvas id="canvas"></canvas>
<script>


    var ctx = document.getElementById("myChart").getContext('2d');

    var myChart = new Chart(ctx, {
        type: 'radar',
        data: {
            labels: ["Appointment", "Social", "Event", "Personal", "Work", "Other"],

            datasets: [
                {
                    label: 'Pull',
                    data: [12, 19, 3, 5, 2, 3],
                    backgroundColor: ['rgba(99, 109, 255, 0.2)',] ,

               },
                {
                    label: 'Meeba',
                    data: [1, 13, 10, 8, 12, 13],
                    backgroundColor: ['rgba(57, 169, 238, 0.2)',]
                },


        ]
    },
        options: {
            scales: { display: false ,
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
<script>
    var canvas = document.getElementById("canvas").getContext('canvas');
    var ctx = canvas.getContext('2d');
    var gradient = ctx.createLinearGradient(0, 0, 200, 0);
    gradient.addColorStop(0, 'green');
    gradient.addColorStop(1, 'white');
    ctx.fillStyle = gradient;
    ctx.fillRect(10, 10, 200, 100);

</script>